### ISSUE TITLE
Logout Redirects to Front-Page

### ISSUE THREAD

**Issue by JessicaInTime** [Gameboyz/theme#11]
When logging out from an article, the login system redirects to the front-page. The correct functionality is to log the user and and have the user stay on the page from where they logged out from.

**Comment by JessicaInTime** [comment]
I don't know if the plugin has that functionality. I did a brief look and didn't see anything in the ultimate member plugin off the bat. Can you take a deeper look and see if you can find anything that would allow the user to logout and stay on the last page they were viewing?

**Comment by 00samer** [comment]
change wp_logout_url() to wp_logout_url(get_permalink()) in wpdiscuz/comment-form/form.php

**Comment by 00salmon** [comment]
Change successful

wpdiscuz/comment-form/form.php
Line 99

wp_logout_url() changed to wp_logout_url(get_permalink())
