### ISSUE TITLE
Limit # of Characters in Article Title 

### ISSUE THREAD

**Issue by JessicaInTime** [Gameboyz/theme#25]
Need to limit the number of characters so it doesn't mess with the styling, must find a sweet spot.

**Comment by Disastrous** [comment]
See link for details. I dont have access to this code. https://wordpress.org/support/topic/limit-title-to-25-characters

**Comment by JessicaInTime** [comment]
i ended up using this plugin: https://wordpress.org/plugins/limit-post-titles/
will have to make note of it in the user manual that it's in-advisable to change this value any higher than what i set it at
