### ISSUE TITLE
Need Login Menu | Navbar

### ISSUE THREAD

**Issue by JessicaInTime** [Gameboyz/theme#5]
Login system should be on nav bar for easy access. If a user is logged in, a drop down menu should be in-place, integrated with ultimate member plugin for profile.

This should also work for high privileged accounts as well (admins, editors, authors).

![screen shot 2015-05-30 at 11 49 27](https://cloud.githubusercontent.com/assets/5874122/7898874/ffa1a7ca-06c2-11e5-8542-3ca8c486a486.png)

**Comment by 00salmon** [comment]
temporary work in progress - need to put this in a hidden div / dropdown of some sort along with 
manual login fields
commit: https://github.com/Gameboyz/theme/commit/31d3f100e507525b360e96df78002a7dd5a5fdce

**Comment by 00salmon** [comment]
getting 404 error when logging out while viewing an article (on live server), do not get the error on localhost server
