### ISSUE TITLE
Configure User Permissions

### ISSUE THREAD

**Issue by JessicaInTime** [Gameboyz/theme#6]
The user role permissions plugin is installed on the public site, with defaults as the current permissions.

**Comment by Disastrous** [comment]
Admin could delete another user     - Fixed
Admin could publish an news story  - Fixed
Editor role is established                  - Fixed
Murray has a role                             - Fixed
Have an integration with UM           - Fixed

**Comment by Disastrous** [comment]
Tested all the different users as well as made sure that everything works well with other plug ins. Permissions have been successfully tested.
